import { AGENT_DEFINITIONS, type AgentDefinition } from '../agents/definitions.js';
import {
  resolveAgentModel,
  resolveAgentModelContext,
  type AgentModelResolutionContext,
} from '../agents/model-routing.js';

export const OMX_MODELS_START_MARKER = '<!-- OMX:MODELS:START -->';
export const OMX_MODELS_END_MARKER = '<!-- OMX:MODELS:END -->';

const TEAM_MODEL_RESOLUTION_END = '</team_model_resolution>';

export interface AgentsModelTableContext extends AgentModelResolutionContext {}

function escapeTableCell(value: string): string {
  return value.replace(/\|/g, '\\|').replace(/\r?\n/g, ' ');
}

function formatRoleLabel(role: string): string {
  return role.includes('(') ? role : `\`${role}\``;
}

function getAgentRecommendedModel(
  agent: AgentDefinition,
  context: AgentsModelTableContext,
): string {
  return resolveAgentModel(agent, context);
}

function getAgentUseCase(agent: AgentDefinition): string {
  return `${agent.description} (${agent.posture}, ${agent.modelClass}, tier=${agent.preferredModelTier})`;
}

function buildTableRow(
  role: string,
  model: string,
  reasoningEffort: string,
  useCase: string,
): string {
  return `| ${escapeTableCell(formatRoleLabel(role))} | ${escapeTableCell(`\`${model}\``)} | ${escapeTableCell(reasoningEffort)} | ${escapeTableCell(useCase)} |`;
}

export function resolveAgentsModelTableContext(
  configTomlContent: string,
  options: {
    codexHomeOverride?: string;
    env?: NodeJS.ProcessEnv;
  } = {},
): AgentsModelTableContext {
  return resolveAgentModelContext(configTomlContent, options);
}

export function buildAgentsModelTable(
  context: AgentsModelTableContext,
  definitions: Record<string, AgentDefinition> = AGENT_DEFINITIONS,
): string {
  const rows = [
    buildTableRow(
      'Frontier (leader)',
      context.frontierModel,
      'high',
      'Primary leader/orchestrator for planning, coordination, and frontier-class reasoning.',
    ),
    buildTableRow(
      'Mini (mid-weight execution)',
      context.miniModel,
      'medium',
      'Explicit role-split lane for mid-weight execution and specialist roles.',
    ),
    buildTableRow(
      'Spark (explorer/fast)',
      context.sparkModel,
      'low',
      'Fast triage, explore, lightweight synthesis, and low-latency routing.',
    ),
    buildTableRow(
      'Subagent default',
      context.subagentDefaultModel,
      'medium',
      'Legacy/default routing for roles that are not explicitly assigned to frontier, mini, or spark tiers.',
    ),
    ...Object.values(definitions).map((agent) =>
      buildTableRow(
        agent.name,
        getAgentRecommendedModel(agent, context),
        agent.reasoningEffort,
        getAgentUseCase(agent),
      ),
    ),
  ];

  return [
    '## Model Capability Table',
    '',
    'Auto-generated by `omx setup` from the current `config.toml` plus OMX model overrides.',
    '',
    '| Role | Model | Reasoning Effort | Use Case |',
    '| --- | --- | --- | --- |',
    ...rows,
  ].join('\n');
}

export function renderAgentsModelTableBlock(
  context: AgentsModelTableContext,
  definitions: Record<string, AgentDefinition> = AGENT_DEFINITIONS,
): string {
  return [
    OMX_MODELS_START_MARKER,
    buildAgentsModelTable(context, definitions),
    OMX_MODELS_END_MARKER,
  ].join('\n');
}

export function upsertAgentsModelTable(
  content: string,
  context: AgentsModelTableContext,
  definitions: Record<string, AgentDefinition> = AGENT_DEFINITIONS,
): string {
  const block = renderAgentsModelTableBlock(context, definitions);
  const startIndex = content.indexOf(OMX_MODELS_START_MARKER);
  const endIndex = content.indexOf(OMX_MODELS_END_MARKER);

  if (startIndex >= 0 && endIndex > startIndex) {
    const replaceEnd = endIndex + OMX_MODELS_END_MARKER.length;
    return `${content.slice(0, startIndex)}${block}${content.slice(replaceEnd)}`;
  }

  const insertionAnchor = `${TEAM_MODEL_RESOLUTION_END}\n\n---`;
  if (content.includes(insertionAnchor)) {
    return content.replace(
      insertionAnchor,
      `${TEAM_MODEL_RESOLUTION_END}\n\n${block}\n\n---`,
    );
  }

  const trailingNewline = content.endsWith('\n') ? '' : '\n';
  return `${content}${trailingNewline}\n${block}\n`;
}
